name: euexia
version: 1.0.0+1
publish_to: none
description: CRUD with Authentication and Authorization using GET X CLI and Supabase.
environment:
  sdk: ">=2.18.5 <3.10.0"

dependencies:
  cupertino_icons: ^1.0.2
  get: ^4.6.5
  supabase_flutter: 2.3.4
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.0.2
  intl: ^0.17.0
  flutter_spinkit: ^5.2.0
  sign_in_button: ^3.0.0
  google_sign_in: ^6.2.1
  gradient_coloured_buttons: ^0.1.0
  modern_textfield: ^0.0.6
  fl_chart: ^0.63.0
  carousel_slider: ^5.0.0
  cached_network_image: ^3.2.0
  flutter_map: ^4.0.0
  latlong2: ^0.8.1
  geocoding: ^2.1.0
  http: ^0.13.3
  image_picker: ^0.8.7+4
   # Nuevas dependencias para la funcionalidad QR
  qr_flutter: ^4.1.0
  share_plus: ^7.0.2
  path_provider: ^2.1.1
  mobile_scanner: ^3.5.0 # Para m칩vil
  universal_html: ^2.2.1 # Para detecci칩n de plataforma
  image_picker_web: ^3.0.1
  kd_utils: ^0.1.0+7 
  flutter_local_notifications: ^18.0.1
  shared_preferences: ^2.0.15
  flutter_launcher_icons: ^0.13.1
  #geolocator: ^10.1.0  # Versi칩n m치s reciente
  #permission_handler: ^10.4.0


dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - assets/
    - .env
  uses-material-design: true

flutter_icons:
  android: true
  ios: true
  image_path: "assets/Logo_color.png"